import "../project.css";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ProjectReader from "../ProjectReader";

type Project = {
  slug:string; number:string; title:string; type:string; intro:string; cover:string;
  role:string; process:string; result:string; duration:string; tools:string;
  story:[string,string,string]; breakdown:{headline:string;mark:string;palette:string[];tokens:[string,string,string];typeCopy:string;colorCopy:string;systemCopy:string;items:[string,string,string]};
};

const projects:Project[] = [
  {slug:"fluid-signal",number:"01",title:"FLUID SIGNAL",type:"AI 视觉传播",intro:"围绕“数字信号如何被看见”，把液态玻璃语言组织成适用于大屏、社交媒体与动态影像的传播系统。",cover:"/case-studies/fluid-signal-applications.png",role:"概念设定 / AI 图像生成 / 图像精修 / 跨屏编排",process:"先定义液态、折射、信号三组视觉变量，再统一曲线方向、透明层级、冰蓝高光与文字安全区。",result:"数字大屏 / 社交封面 / 落地页主视觉 / 动态关键帧",duration:"3 周 · 2026",tools:"生成式 AI / Photoshop / Figma",story:["把生成图像，变成可持续调用的传播语言。","生成式图像容易停留在单张效果图。本项目从传播尺寸与阅读场景出发，为画面建立统一的构图、安全区与材质规则。","最终形成横屏、竖屏和动态关键帧之间可延展的视觉系统，让每次输出都保留同一组识别特征。"],breakdown:{headline:"液态、折射与跨屏传播",mark:"流·信",palette:["深石墨","冰蓝","云白","透银"],tokens:["液态玻璃","冰蓝折射","跨屏安全区"],typeCopy:"用曲线、透明层叠和留白组织轻盈连续的空间秩序。",colorCopy:"深石墨稳定信息重心，冰蓝与透银负责折射和数字质感。",systemCopy:"同一主视觉可适配数字大屏、社交封面与动态关键帧。",items:["数字大屏","社交封面","动态关键帧"]}},
  {slug:"lumen-brand-system",number:"02",title:"LUMEN",type:"未来品牌系统",intro:"以“光是信息的入口”为概念，从光束汇聚的几何逻辑出发，建立标识、版式、材质与数字触点的统一系统。",cover:"/case-studies/lumen-applications.png",role:"品牌概念 / 标识方向 / 视觉系统 / 应用设计",process:"将光束轨迹抽象为识别母题，通过黑白辨识、比例校准和多触点应用测试确定规则。",result:"品牌标识 / 文具 / 空间海报 / 移动界面 / 活动证件",duration:"4 周 · 2026",tools:"Illustrator / Photoshop / Figma",story:["让“光”从概念，变成清晰的品牌规则。","项目不依赖常见的渐变和发光特效，而是从光束汇聚的结构中提炼标识母题，并用留白控制未来感。","钴蓝只作为信息焦点出现，银灰材质连接纸张与数字界面，使不同触点保持统一而克制。"],breakdown:{headline:"光束、汇聚与品牌触点",mark:"光·束",palette:["冷白","雾银","墨黑","钴蓝"],tokens:["汇聚光束","银灰材质","钴蓝焦点"],typeCopy:"几何标识与细线网格共同建立清晰、有呼吸感的识别秩序。",colorCopy:"冷白与雾银构成主体，墨黑承载信息，钴蓝强调关键节点。",systemCopy:"规则延展到品牌文具、空间海报和活动证件。",items:["品牌文具","空间海报","活动证件"]}},
  {slug:"yemu-tea-packaging",number:"03",title:"YEMU",type:"当代茶礼包装",intro:"面向年轻礼赠场景，以纤维纸、森林绿和克制金色细节，建立礼盒、茶罐与手提袋之间统一的包装家族。",cover:"/case-studies/yemu-packaging-applications.png",role:"品牌命名 / 包装层级 / 材质色彩 / 应用展示",process:"拆分自饮与礼赠需求，通过材料、色带、图形比例和开盒层级建立产品关系。",result:"礼盒 / 茶罐 / 独立茶袋 / 手提袋 / 品鉴卡",duration:"4 周 · 2026",tools:"Illustrator / Photoshop / AI Mockup",story:["让自然质感，进入清晰的礼赠体系。","纤维纸负责触感与温度，森林绿建立品类识别，哑金只用于封签和局部信息，避免传统茶礼包装的元素堆叠。","礼盒、茶罐、独立袋与手提袋遵循同一图形比例，在不同容量中形成明确的家族关系。"],breakdown:{headline:"纤维、森林与礼赠秩序",mark:"野·木",palette:["纤维白","森林绿","哑金","茶雾灰"],tokens:["纤维纸张","森林绿色","礼盒层级"],typeCopy:"叶片图形被压缩为简洁标识，包装层级通过比例而非装饰区分。",colorCopy:"纤维白保留自然触感，森林绿负责识别，哑金提升礼赠细节。",systemCopy:"礼盒、金属茶罐与礼袋共同构成完整的产品家族。",items:["礼盒系统","金属茶罐","礼袋卡片"]}},
  {slug:"ai-visual-lab",number:"04",title:"AI 创意视觉探索",type:"生成式视觉",intro:"围绕透明、流动与折射进行材质实验，通过构图筛选、局部修复和统一调色，形成一组未来感数字封面。",cover:"/projects/ai-visual-exploration.png",role:"提示词设计 / AI 图像生成 / 图像精修 / 主视觉编排",process:"建立关键词情绪板，测试多组材质与构图，再对稳定画面进行修瑕、调色与标题适配。",result:"数字封面 / 主视觉画面 / 材质实验样本",duration:"3 周 · 2026",tools:"生成式 AI / Photoshop",story:["让视觉实验，留下清晰的选择依据。","本组练习专注透明、流动和精密三种感受，观察玻璃、液体与金属在不同光线中的画面张力。","输出以单幅数字封面为核心，保留生成实验的开放感，同时通过后期处理建立统一完成度。"],breakdown:{headline:"材质、光线与空间",mark:"透·流",palette:["深空灰","雾银","云白","冰蓝"],tokens:["透明层叠","冰蓝折射","环形流线"],typeCopy:"透明层叠和曲线运动共同塑造连续的空间感。",colorCopy:"银白与冰蓝模拟玻璃折射，深灰稳定画面重心。",systemCopy:"视觉实验被整理为主视觉、局部材质与版式样本。",items:["主视觉","材质样本","版式实验"]}},
  {slug:"future-brand-system",number:"05",title:"品牌视觉系统设计",type:"品牌主视觉",intro:"以几何标识、冷白空间、钴蓝强调色和克制排版建立视觉记忆，探索标识与基础品牌物料之间的秩序。",cover:"/projects/brand-visual-system.png",role:"主视觉方向 / 几何标识 / 色彩关系 / 提案版式",process:"确定理性、轻量、未来感的视觉关键词，围绕符号比例、留白关系和强调色组织画面。",result:"标识方向 / 品牌海报 / 提案封面 / 社媒主图",duration:"3 周 · 2026",tools:"Illustrator / Photoshop",story:["用有限的元素，建立明确的品牌气质。","几何形态经过比例和缩放测试，在小尺寸中仍保持可辨识；大面积留白让符号成为稳定焦点。","这一作品专注视觉识别基础，不承担完整品牌战略，而是验证标识、版式与色彩能否形成一致气质。"],breakdown:{headline:"标识、留白与强调色",mark:"轻·序",palette:["冷白","雾银","墨黑","钴蓝"],tokens:["几何符号","留白网格","钴蓝锚点"],typeCopy:"几何标识和细线框架建立轻量、清晰的阅读秩序。",colorCopy:"冷白与雾银保持克制，墨黑承载标题，钴蓝集中识别。",systemCopy:"主视觉延展至提案封面、品牌海报与社交主图。",items:["提案封面","品牌海报","社交主图"]}},
  {slug:"digital-narrative-space",number:"06",title:"数字传播视觉设计",type:"跨屏视觉",intro:"围绕线上内容的多屏阅读问题，让桌面长页、移动卡片与社交媒体切片保持统一的信息层级。",cover:"/projects/digital-communication-system.png",role:"信息层级 / 页面视觉 / 跨屏适配 / 内容模块",process:"拆分标题、图像、引导和数据模块，建立可复用版式，并验证横屏、竖屏与方图比例。",result:"桌面长页 / 移动卡片 / 社交切片",duration:"2 周 · 2026",tools:"Figma / Photoshop",story:["让同一份内容，在不同屏幕保持节奏。","桌面端负责完整叙事，移动端强调快速扫描，社交切片则保留最强的信息锚点。","统一裁切比例、编号系统和色块位置，让内容改变尺寸时不失去视觉连续性。"],breakdown:{headline:"跨屏、节奏与信息",mark:"屏·流",palette:["深海蓝","数字蓝","珊瑚红","暖象牙"],tokens:["图像裁切","信息编号","跨屏模块"],typeCopy:"编号与模块化卡片组织不同屏幕中的阅读顺序。",colorCopy:"深海蓝稳定底色，数字蓝建立技术感，珊瑚红只用于转场。",systemCopy:"内容模块可在桌面、移动端与社交媒体中重组。",items:["桌面长页","移动卡片","社交切片"]}},
  {slug:"cultural-poster-series",number:"07",title:"城市记忆海报计划",type:"系列海报",intro:"以城市漫游、旧影像和时间痕迹为主题，把摄影碎片、粗粝纹理与纵向红色结构组成系列海报。",cover:"/projects/cultural-poster-series.png",role:"主题策划 / 系列海报 / 图像拼贴 / 展览视觉",process:"提炼城市记忆关键词，选择建筑、水面和人物片段，再用统一色彩与纵向结构串联系列。",result:"系列海报 / 邀请物料 / 展览导视 / 社交预告",duration:"2 周 · 2026",tools:"Photoshop / Illustrator",story:["把零散的城市片段，重新组织成可阅读的记忆。","黑白摄影与粗粝纹理保留旧影像的不完整感，建筑轮廓和行走的人形成重复线索。","纵向朱红结构既是视觉锚点，也是时间轴，让每张海报独立又保持系列关系。"],breakdown:{headline:"城市、时间与记忆",mark:"城·迹",palette:["墨黑","旧纸米白","朱红","石灰灰"],tokens:["旧纸纹理","朱红竖线","城市剪影"],typeCopy:"纵向结构连接海报，摄影碎片保留记忆的模糊感。",colorCopy:"米白和墨黑形成历史质感，朱红作为时间标记贯穿系列。",systemCopy:"主视觉延展到海报、邀请函、导视和展览空间。",items:["系列海报","展览导视","邀请物料"]}},
  {slug:"tea-packaging-system",number:"08",title:"自然茶品牌包装",type:"包装视觉",intro:"从茶芽形态、纤维纸触感与日常饮茶出发，探索自然材料、深绿色识别和金属容器的包装关系。",cover:"/projects/tea-packaging-system.png",role:"包装概念 / 图形延展 / 色彩材质 / 套装组合",process:"从茶叶品类和日常使用场景出发，设计图形、包装层级、色彩材质和组合关系。",result:"盒装方向 / 罐装方向 / 内袋图形 / 礼袋延展",duration:"3 周 · 2026",tools:"Illustrator / Photoshop",story:["从一片茶叶出发，建立自然、轻松的包装体验。","叶片被分解为可重复使用的图形单元，米白纤维纸传递手作温度，深绿建立稳定的品类识别。","相比 YEMU 的礼赠体系，本项目更强调日常陈列、轻量组合和亲和的饮茶体验。"],breakdown:{headline:"自然、材料与日常陈列",mark:"叶·息",palette:["纤维米白","茶叶绿","深林绿","陶土灰"],tokens:["叶片单元","纤维触感","日常组合"],typeCopy:"叶片图形以重复和留白形成轻松、自然的包装节奏。",colorCopy:"米白传递温度，两级绿色区分信息与品类。",systemCopy:"盒装、罐装和内袋围绕日常购买场景自由组合。",items:["盒装方向","罐装方向","内袋图形"]}},
  {slug:"motion-identity",number:"09",title:"生成式动态识别",type:"动态视觉",intro:"用金属带、粒子轨迹和边缘光建立可循环变化的视觉核心，让静态符号拥有时间感和运动秩序。",cover:"/projects/motion-identity.png",role:"动态概念 / 形态设计 / 关键帧设定 / 生成视觉",process:"设计基础形态与运动规则，推导聚合、旋转、释放三种状态，并提取关键帧用于展示。",result:"片头识别 / 转场规则 / 循环背景 / 关键帧",duration:"3 周 · 2026",tools:"After Effects / 生成式 AI",story:["让识别系统不仅有形状，也拥有时间。","三条金属带相互穿插，旋转、聚合和释放构成可重复的运动语法。","粒子轨迹记录形态变化，紫蓝边缘光强化空间深度，使系统适合片头、转场与数字界面。"],breakdown:{headline:"形态、运动与时间",mark:"聚·释",palette:["近黑","紫蓝","铬银","轨迹灰"],tokens:["金属带","边缘光","粒子轨迹"],typeCopy:"金属带通过旋转、聚合与释放形成循环运动语法。",colorCopy:"黑色空间突出轮廓，紫蓝边缘光记录运动，铬银保留反射。",systemCopy:"动态核心可拆分为片头、转场、循环背景和关键帧。",items:["片头识别","转场规则","循环背景"]}}
];

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params; const project=projects.find(item=>item.slug===slug);
  if(!project) return {title:"作品未找到｜张顺富作品集"};
  return {title:`${project.title}｜张顺富作品集`,description:project.intro,openGraph:{title:`${project.title}｜张顺富作品集`,description:project.intro,images:[{url:project.cover,alt:project.title}]}};
}

export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const index=projects.findIndex(p=>p.slug===slug); if(index<0) notFound();
  const project=projects[index], prev=projects[(index-1+projects.length)%projects.length], next=projects[(index+1)%projects.length], b=project.breakdown;
  return <main className={`detail detail-project-${project.number}`} id="main-content"><ProjectReader />
    <nav className="detail-nav" aria-label="作品导航"><Link href="/#work">← 返回作品集</Link><Link className="detail-logo" href="/">张顺富<sup>®</sup></Link><a href="mailto:sheriff001@foxmail.com">联系合作 ↗</a></nav>
    <header className="detail-hero"><div className="detail-label"><span>作品 {project.number}</span><span>{project.type} · 自主命题作品</span></div><h1>{project.title}</h1><p>{project.intro}</p><div className="detail-tags">{project.role.split(" / ").map(tag=><span key={tag}>{tag}</span>)}</div></header>
    <figure className="detail-cover"><img src={project.cover} alt={project.title} loading="eager" decoding="async" fetchPriority="high"/></figure>
    <section className="detail-info" id="overview"><div><small>核心命题</small><p>{project.story[0]}</p></div><div><small>设计动作</small><p>{project.role}</p></div><div><small>输出场景</small><p>{project.result}</p></div><div><small>作品属性</small><p>自主命题 · {project.type}</p></div></section>
    <section className="detail-story" id="method"><aside className="detail-story-heading"><span>设计方法</span><strong>项目概览</strong><ol>{b.tokens.map((token,i)=><li key={token}><i>{String(i+1).padStart(2,"0")}</i>{token}</li>)}</ol></aside><div><h2>{project.story[0]}</h2><p>{project.story[1]}</p><p>{project.story[2]}</p><p className="detail-process-note"><strong>过程重点</strong>{project.process}</p></div></section>
      <section className={`detail-breakdown breakdown-${project.number}`} id="breakdown"><div className="breakdown-title"><span>视觉拆解</span><div><h2>{b.headline}</h2><div className="breakdown-tokens">{b.tokens.map(token=><b key={token}>{token}</b>)}</div></div></div><div className="breakdown-board"><div className="breakdown-type"><small>视觉构成</small><div className="breakdown-signature" data-visual={project.slug} aria-hidden="true"><i/><i/><i/></div><strong>{b.mark}</strong><p>{b.typeCopy}</p></div><div className="breakdown-color"><small>色彩关系</small><div className="palette" data-palette={project.slug}>{b.palette.map(color=><i key={color} aria-label={color}/>)}</div><div className="palette-labels">{b.palette.map(color=><span key={color}>{color}</span>)}</div><p>{b.colorCopy}</p></div><div className="breakdown-system"><small>系统与延展</small>{b.items.map((item,i)=><b key={item}>{String(i+1).padStart(2,"0")}<em>{item}</em></b>)}<p>{b.systemCopy}</p></div></div></section>
    <section className="detail-next" id="next-project"><p>继续浏览</p><div><Link className="detail-next-card previous" href={`/projects/${prev.slug}`}><img src={prev.cover} alt="" loading="lazy"/><small>上一作品 · {prev.number}</small><span>{prev.title}</span><em>{prev.type}</em></Link><Link className="detail-next-card next" href={`/projects/${next.slug}`}><img src={next.cover} alt="" loading="lazy"/><small>下一作品 · {next.number}</small><span>{next.title}</span><em>{next.type}</em></Link></div></section>
    <footer className="detail-footer"><h2>让我们一起创造<br/><em>有意义的作品。</em></h2><a href="mailto:sheriff001@foxmail.com">SHERIFF001@FOXMAIL.COM ↗</a><p>© 2026 张顺富 · 视觉 / AI / 品牌设计师</p></footer>
  </main>;
}
